version: "3.9"

services:
  db:
    image: postgres:16
    container_name: gestorclub-db
    restart: always
    environment:
      POSTGRES_DB: gestorClubDB
      POSTGRES_USER: jose
      POSTGRES_PASSWORD: jose1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gestorclub-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jose -d gestorClubDB"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: gestorclub-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gestorClubDB
      SPRING_DATASOURCE_USERNAME: jose
      SPRING_DATASOURCE_PASSWORD: jose1234
    ports:
      - "8080:8080"
    networks:
      - gestorclub-network

volumes:
  pgdata:

networks:
  gestorclub-network:
